package de.hahn.blog.dbinfofromapp.model.adfbc.facade.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jan 01 12:47:56 CET 2021
// ---------------------------------------------------------------------
public interface BDBIFAAppModule extends ApplicationModule {
    String getApplicationName();
}

