package de.hahn.blog.empapplib.adfbc.facade.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jan 01 12:30:08 CET 2021
// ---------------------------------------------------------------------
public interface EmpAppLibModule extends ApplicationModule {
    String getApplicationName();
}

