package de.hahn.blog.depapplib.adfbc.facade.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jan 01 12:51:43 CET 2021
// ---------------------------------------------------------------------
public interface DepLibAppModule extends ApplicationModule {
    String getApplicationName();
}

