package de.hahn.blog.dbinfofromapp.model.adfbc.facade;

import de.hahn.blog.baseclasses.model.adfbc.facade.BaseApplicationModuleImpl;
import de.hahn.blog.dbinfofromapp.model.adfbc.facade.common.BDBIFAAppModule;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jan 01 12:46:40 CET 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BDBIFAAppModuleImpl extends BaseApplicationModuleImpl implements BDBIFAAppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public BDBIFAAppModuleImpl() {
    }

    /**
     * Container's getter for CountriesView1.
     * @return CountriesView1
     */
    public ViewObjectImpl getCountriesView1() {
        return (ViewObjectImpl) findViewObject("CountriesView1");
    }

    /**
     * Container's getter for LocationsView1.
     * @return LocationsView1
     */
    public ViewObjectImpl getLocationsView1() {
        return (ViewObjectImpl) findViewObject("LocationsView1");
    }

    /**
     * Container's getter for RegionsView1.
     * @return RegionsView1
     */
    public ViewObjectImpl getRegionsView1() {
        return (ViewObjectImpl) findViewObject("RegionsView1");
    }

    /**
     * Container's getter for CountriesView2.
     * @return CountriesView2
     */
    public ViewObjectImpl getCountriesView2() {
        return (ViewObjectImpl) findViewObject("CountriesView2");
    }

    /**
     * Container's getter for LocationsView2.
     * @return LocationsView2
     */
    public ViewObjectImpl getLocationsView2() {
        return (ViewObjectImpl) findViewObject("LocationsView2");
    }

    /**
     * Container's getter for CountrRegFkLink1.
     * @return CountrRegFkLink1
     */
    public ViewLinkImpl getCountrRegFkLink1() {
        return (ViewLinkImpl) findViewLink("CountrRegFkLink1");
    }

    /**
     * Container's getter for LocCIdFkLink1.
     * @return LocCIdFkLink1
     */
    public ViewLinkImpl getLocCIdFkLink1() {
        return (ViewLinkImpl) findViewLink("LocCIdFkLink1");
    }

    /**
     * Container's getter for EmpAppLibModule1.
     * @return EmpAppLibModule1
     */
    public ApplicationModuleImpl getEmpAppLibModule1() {
        return (ApplicationModuleImpl) findApplicationModule("EmpAppLibModule1");
    }

    public String getApplicationName() {
        String name = super.getTransactionName();
        return name;
    }

    /**
     * Container's getter for DepLibAppModule1.
     * @return DepLibAppModule1
     */
    public ApplicationModuleImpl getDepLibAppModule1() {
        return (ApplicationModuleImpl) findApplicationModule("DepLibAppModule1");
    }
}

